config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'signup', to: 'users#new'
  
  resources :users do
    member do
      get :likes
      get :mylog
      get :index
    end 
  end 
#put 'edit', to: 'users#update'
  
  
  #get 'comment', to: 'users#commnet'
  #post 'comment', to: 'comments#create'
  

  resources :documents do
    resources :comments, only: [:create, :destroy]
  end 
    
  
  
  get 'documents/download/:id' => 'documents#download', as: :download
  
  resources :posts, only: [:create, :destroy]
  
 
  get  'upload', to: 'uploader#form'
  post 'uploader/upload'
  
  
  resources :favorites, only: [:create, :destroy]


  resources :comments, only: [:create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email.downcase! }
    validates :name, presence: true, length:{ maximum: 20}
    validates :email, presence: true, length:{ maximum: 255 },
                      format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                      uniqueness: { case_sensitive: false }
    validates :introduce, length:{ maximum: 50 }                  
    mount_uploader :image, ImageUploader                  
    
    
    has_secure_password
    has_many :documents,dependent: :destroy
    
    has_many :favorites,dependent: :destroy
    has_many :likes, through: :favorites, source: :document
    has_many :comments,dependent: :destroy
    has_many :log, through: :comments, source: :document
    
    
    
    def like(document)
        unless self.documents == document
            self.favorites.find_or_create_by(document_id: document.id)
        end 
    end 
    
    def dislike(document)
        favorite = self.favorites.find_by(document_id: document.id)
        favorite.destroy if favorite
    end 
    
    def favorite?(document)
        self.likes.include?(document)
    end 
    
    def comment
       self.comments.create_by(document_id: document.id)
    end 
    
        
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:edit, :update, :destroy]
  
  
  
  def index
    @users = User.all
    
  end

  def show
    @user = User.find(params[:id])
    @documents = @user.documents.order(id: :desc).page(params[:page])
    counts(@user)
    @favorites = @user.likes.page(params[:page])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:success] = '登録しました'
      @user && @user.authenticate(@user.password)
    session[:user_id] = @user.id
      redirect_to @user
    else
      flash.now[:danger] = '登録できませんでした'
      render :new
    end 
  end

  def edit
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to root_path
    end 
  end

  def update
    @user = User.find(params[:id])
    
    if @user.update(user_params)
      flash[:success] = '更新しました'
      redirect_to @user
    else
      flash.now[:danger] = "更新できませんでした"
      render :edit
    end 
  end


  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:success] = "See You Again!"
    redirect_to root_url
  end
  
  def likes
    @user = User.find(params[:id])
    counts(@user)
    #counts(@user)
        #@likes = @user.favorites.page(params[:page])
    @likes = @user.likes.page(params[:page]).per(18).order('updated_at DESC')
  end 
  
  def mylog
    @user = User.find(params[:id])
    counts(@user)
    @mylog = @user.documents.page(params[:page]).per(18).order('updated_at DESC')
  end 
  
  

private

  def user_params
    params.require(:user).permit(:name, :email, :introduce, :password, :password_confirmation, :image, :image_cache)
  end 


  
  
end

app/views/users/_user_info.html.erb
<div class="row" id="user_info">
  <div class="offset-1 col-lg-2">
    
      
          <% if @user.image? %>
            <p class="user-image"><%= cl_image_tag @user.image.thumb.url, :size =>'180x180', id: 'user-image' %></p>
          <% else %>
            <p class="user-image"><%= cl_image_tag "https://res.cloudinary.com/hkc1jmpeu/image/upload/q_50/v1569112418/194.jpg", :size =>'180x180', id: 'user-image' %></p>
          <% end %>
        
      
      <% if @user == current_user %>
               <%= link_to '編集', edit_user_path, data: {"turbolinks" => false} %>
      
      <% end %>
   
  </div>

  <div class="col-lg-5">
   
       <h3><%= @user.name %></h3>
       
       <div class="box11">
       <p id="introduce"><%= @user.introduce %></p>
       </div>
  </div>
</div>

  <div class="col-sm-12">
    <ul class="nav nav-tabs nav-justified mb-3">
        
        
        
      <li class="nav-item"><a href="<%= mylog_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(mylog_user_path(@user)) %>">投稿 <span class ="badge badge-secondary">
      <%= @count_mylog %></span></a></li>
      
      <li class="nav-item"><a href="<%= likes_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(likes_user_path(@user)) %>">保存 <span class ="badge badge-secondary">
      <%= @count_likes %></span></a></li>
    </ul>
  </div>

app/views/users/edit.html.erb
<div class="sign up offset-lg-1">
    <h1>プロフィール編集</h1>
</div>


           
    <%= form_with(model: @user, local: true) do |f| %>
        <div class="row">
                <div class="offset-lg-1 col-lg-4">
                    <%= render 'layouts/error_messages', model: f.object %>
                    <div class="form-group">
                        <div class="card">
                            <div class="card-header">
                                <%= f.label :image, 'クリックで画像変更' %>
                        
                                <div id="img_field" onClick="$('#file').click()" >
                                    <% if @user.image.url.present? %>
                                      <%= image_tag @user.image.thumb.url, :size =>'180x150' %>
                                    <% else %>
                                      <%= image_tag 'no_image.jpg', :size =>'180x150' %>
                                    <% end %>
                                </div>
                                <%= f.file_field :image, class: "image", style: "display:none;", id: "file" %>
                                <%= f.hidden_field :image_cache %>
                            </div>
                        </div>
                    </div>
                </div>
         
                <div class="col-lg-6">   
                    <div class="form-group">
                        <%= f.label :name, '名前' %>
                        <%= f.text_field :name, class: 'form-control' %>
                    </div>
                    
                    <div class="form-group">
                        <%= f.label :introduce, '自己紹介' %>
                        <%= f.text_area :introduce, rows: 5, class: 'form-control' %>
                    </div>      
                </div>
            <div class="submit offset-8 col-3">
                <%= f.submit '登録', class: 'btn btn-primary btn-block' %>
             </div>   
           <% if current_user == @user %>
           <div class="delete_user offset-9">
             <%= link_to 'アカウントを削除する', @user, method: :delete, data: {confirm: 'これまでの投稿もすべて削除されます。本当に削除してよろしいですか' }, class: "badge badge-secondary" %>
             </div>
            <% end %>
        </div>
     <% end %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/likes.html.erb
<%= render 'users/user_info', user: @user %>

      
 <!--     
      <li class="nav-item"><a href="#" class="nav-link">コメント</a></li>
   
    -->
 
    <%= render 'layouts/card_list', documents: @likes %>

<div class="offset-lg-4">
<%= paginate @likes %>
</div>

app/views/users/mylog.html.erb
<%= render 'users/user_info', user: @user %>

    <%= render 'layouts/card_list', documents: @mylog %>

<div class="offset-lg-4">
<%= paginate @mylog %>
</div>

app/views/users/new.html.erb
<div class="offset-5 sign_up">
    <h1>新規登録</h1>
</div>

<div class="row">
    <div class="col-sm-6 offset-sm-3">
        
        <%= form_with(model: @user, local: true) do |f| %>
         <%= render 'layouts/error_messages', model: f.object %>
 
        <div class="form-group">
            <%= f.label :name, 'ユーザー名' %>
            <%= f.text_field :name, class: 'form-control' %>
        </div>

        <div class="form-group">
            <%= f.label :email, 'メールアドレス' %>
            <%= f.email_field :email, class: 'form-control' %>
        </div>
    
        <div class="form-group">
            <%= f.label :password, 'パスワード' %>
            <%= f.password_field :password, class: 'form-control' %>
        </div>
        
        <div class="form-group">
            <%= f.label :password_confirmation, 'パスワード確認' %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
        </div>
        
        <%= f.submit '登録', class: 'btn btn-primary btn-block' %>
    <% end %>
    </div>
</div>

app/views/users/show.html.erb
<%= render 'users/user_info', user: @user %>


      
   <!--   
      <li class="nav-item"><a href="#" class="nav-link">コメント</a></li>
    -->
    </ul>
  </div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>

app/views/users/users-index.html.erb
<div class="card-deck", id="card_list">

     <% @users.each do |user| %>
        <div class="col-lg-4" id="card">
            <div class="card bg-light">
                
             
                  <div class="card-body">
                      <div class="row">
                          <div class="col-lg-5 col-sm-3">
                            <% if document.posts.first.image.present? %>
                                <%= cl_image_tag user.image.thumb.url, :width=>180, :height=>180, class:'img-fluid' %>
                             <% else %>
                                <%= cl_image_tag "https://res.cloudinary.com/hkc1jmpeu/image/upload/v1569026462/186.jpg", :width=>180, :height=>180, class:'img-fluid' %>　<!--画像ないときの画像を決める   保存用　document.posts.first.image.thumb.url-->
                             <% end %>
                          </div>
                          <div class="col-lg-7 col-sm-9">
                                <h4 class="card-title"><%= user.name.truncate(18) %></h4>
    
                                <p class="card-text"><%= user.introduce.truncate(30) %></p>
                            <!---    <p class="card-text"><%#= document.subject %>：<%#= document.content %></p> --->
        
                                 
                          </div>
                      </div>
   
                  </div>
            </div>
        </div>  
    <% end %> 
    

</div>


    