config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'signup', to: 'users#new'
  
  resources :users do
    member do
      get :likes
      get :mylog
      get :index
    end 
  end 
#put 'edit', to: 'users#update'
  
  
  #get 'comment', to: 'users#commnet'
  #post 'comment', to: 'comments#create'
  

  resources :documents do
    resources :comments, only: [:create, :destroy]
  end 
    
  
  
  get 'documents/download/:id' => 'documents#download', as: :download
  
  resources :posts, only: [:create, :destroy]
  
 
  get  'upload', to: 'uploader#form'
  post 'uploader/upload'
  
  
  resources :favorites, only: [:create, :destroy]


  resources :comments, only: [:create, :destroy]
end

app/views/layouts/_card_list.html.erb
<div class="card-deck", id="card_list">

     <% documents.each do |document| %>
        <div class="col-lg-4" id="card">
            <div class="card bg-light">
                
             
                  <div class="card-body">
                      <div class="row">
                      <div class="col-lg-5 col-sm-3">
                        <% if document.posts.first.image.present? %>
                            <%= cl_image_tag document.posts.first.image.thumb.url, :width=>180, :height=>180, class:'img-fluid' %>
                         <% else %>
                            <%= cl_image_tag "https://res.cloudinary.com/hkc1jmpeu/image/upload/v1569026462/186.jpg", :width=>180, :height=>180, class:'img-fluid' %>　<!--画像ないときの画像を決める   保存用　document.posts.first.image.thumb.url-->
                         <% end %>
                      </div>
                      <div class="col-lg-7 col-sm-9">
                            <h4 class="card-title"><%= document.title.truncate(18) %></h4>

                            <p class="card-text"><%= document.goal.truncate(30) %></p>
                        <!---    <p class="card-text"><%#= document.subject %>：<%#= document.content %></p> --->
                            <p><%= render 'documents/tag_list', document: document %></p>
                             
                      </div>
                      </div>
                   <p>投稿者　
                   <%= document.user.name %>
                   <%= link_to '指導案を見る', document_path(document.id) %>
                    </p>
                    <% if logged_in? %>
                    <%= render 'favorites/favorite_button', document: document %>
                <% end %>
                    
                  </div>
            </div>
        </div>  
    <% end %> 
    

</div>


    

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
    <div id="error_explanation" class="alert alert-warning">
        <ul class="mb-0">
            <% model.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="header">
    <nav class="navbar navbar-expand-sm navbar-dark" style="background-color:#333333">
        <a class="navbar-brand offset-1" href="/" id="top">指導案Labo</a>
        
        
    <%= search_form_for @search do |f| %>
      <div class="actions">
        <%= f.label :title_or_goal__or_preparatioin_or_explanation_or_school_or_grade_or_subject_or_content_or_tags_name, '指導案を探す', :class => 'search_name_here' %>
        <%= f.search_field :title_or_goal_or_preparation_or_explanation_or_school_or_grade_or_subject_or_content_or_tags_name_cont %>
        
      <%= f.submit "検索" , :class => 'search' %></div>
    <% end %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
            <span class="navbar-toggler-icon"></span>
        </button>
        
        <div class="collpase navbar-collapse justify-content-end" id ="navbarSupportedContent">
            <ul class="navbar-nav">
              <li class="nav-item"><a class="nav-link">ユーザー</a></li>
            <% if logged_in? %>
            
            <li class="nav-item dropdown"></li>
            　 <li class="navbar"><%= link_to new_document_path, :class=> 'add', data: {"turbolinks" => false} do %>
            　 <i class="fas fa-file-upload", id="nav_icon"></i>投稿
            　 <% end %>
            　 </li>
               <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"><i class="fas fa-user", id="nav_icon"></i><%= current_user.name %></a>
               <ul class ="dropdown-menu dropdown-menu-right">
                    <li class="nav-drop-item" ><%= link_to 'プロフィール', user_path(current_user.id) %></li> 
                    <li class="nav-drop-item" id="drop"><%= link_to 'ログアウト', logout_path, method: :delete %></li>       
                </ul>
            <% else %>
                <li class="nav-item"><%= link_to '登録', signup_path, class: 'nav-link' %></li>
                <li class="nav-item"><%= link_to 'ログイン', login_path, class: 'nav-link' %></li>
            <% end %>
                
            </ul>
        </div>
    </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang ="ja" prefix="og: http://opg.me/ns#">
  <head>
    <%= display_meta_tags(default_meta_tags) %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="指導案データベースサイトです。指導案の閲覧、ダウンロードができます。研究授業に向けて作った指導案を共有して、より良い授業を作りましょう。">
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    
    
    <meta property="og:url" content="https://www.shidouan-lab.com" />
    <meta property="og:title" content="指導案ラボ" />
    <meta property="og:type" content="website">
    <meta property="og:description" content="指導案共有サイトです。指導案の閲覧、ダウンロードができます。研究授業に向けて作った指導案を共有して、より良い授業を作りましょう。" />
    <meta property="og:image" content="https://res.cloudinary.com/hkc1jmpeu/image/upload/v1569754088/2afb6497a3b5867f4f02e8459cee7e1f_o1mdfx" />
    <meta property="fb:app_id" content="#" />
    <meta property="og:site_name" content="https://res.cloudinary.com/hkc1jmpeu/image/upload/v1569329426/224.jpg" />
    <meta property="og:locale" content="ja_JP" />
    
    
    <meta name="twitter:card" content="summary" />
    <meta name="twitter:site" content="@deen5y" />
    <meta name="twitter:description" content="指導案共有サイトです。指導案の閲覧、ダウンロードができます。研究授業に向けて作った指導案を共有して、より良い授業を作りましょう。" />
    <meta name="twitter:image:src" content="https://res.cloudinary.com/hkc1jmpeu/image/upload/v1569329426/224.jpg" />

    <title>指導案ラボ</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

   <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  
  

    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
   
  </head>

  <body>
    <div class="inner">
      <%= render 'layouts/navbar' %>
  
      <%=render 'layouts/flash_messages' %>
      <%= yield %>
    </div>
    
  </body>
</html>